### ISSUE TITLE
No data :-(

### ISSUE THREAD

**Issue by RStadlmair** [johnny-co/MMM-OpenSprinkler#1]
Hi Johnny-co !

Its great that you develop a Module for OS. immediately installed it and tested, unfortuonately i dont get any data on the mirror.
My config file loogs loke this:
		{
			module: 'MMM-OpenSprinkler',
			position: 'top_left',
			config: {
				osName: '7Haus',
				osIP: 'local.dnsname',
				osPassword: 'myplaintextpassword',
				items: [ 'sun', 'raindelay', 'waterlevel', 'programrunning', 'sn'],
			},
		},

but i get a no-show on the screen. How can i help making this work (logs, ...) because i am really interested in making this work.

Regards/Roman

**Comment by johnny-co** [comment]
I'd love to hear it working for you. A couple of questions:
1) if you remove the osIP and osPassword, the default will go to demo.opensprinkler.com 's public facing sprinkler and should give you sprinkler activity/status. Is that working?
2) Try to use your local IP address instead of the dns name. I noticed on my opensprinker system, the IP is set via DHCP and is something like 192.168.0.104 with the host name of HS200. I am hardwired into OS not wifi. and i can not connect via hostname. Did you find a way to set a unique host name in OS? I have not found that in the documentation anywhere.
3) The OS wifi has trouble staying connected and i have a support ticket into them but have not heard back. My work arround is to use the ethernet cable.

**Comment by johnny-co** [comment]
I attempted to use the nslookup to get the dns name, for my OS its ENC28J6225E8 but neither the browser (chrome) nor the nodehelper can connect to it. However the IP address connects just fine in both browser and MM-OS nodehelper.

**Comment by RStadlmair** [comment]
Hi johnny-co!

Thanks for your help.

It doenst work with the demo.opensprinkler.com settings on my box. 
I didnt update my Magicmirror for quite a long time (282 commits behind current).
Are you up2date with your MM ?

Let me try updating the MM an test again, then i give you feedback. Any Other info (logs...) i can post here ?
R.

**Comment by johnny-co** [comment]
I am up to date with MM as of a week or so ago. once you get MM updated, I think the best approach may be to get demo.opensprinkler.com working as they should work out of the box. You can leave the config mostly empty like this and it should connect to demo.opensprinkler.com,
{
module: 'MMM-OpenSprinkler',
position: 'top_left',
config: {},
},

I'll also double check i have the latest files in github. I wish i knew what log files to ask for but this is my first module and my understanding is limited as i havent coded in over a decade.

**Comment by johnny-co** [comment]
I uploaded all the files again. there are newer files but i did not recall it being neccessary. i am trying to get a good countdown timer working. i just removed all other modules in my MM config and only used the OS with defaults and it successfully connects to demo.opensprinkler.com. it shows sunrise, sunset, water level and any program running. also be patience it can take 30 seconds to load the first time, which is too long but havent figured out where the delay is just yet. but once loaded it workings fine. Also are you seeing the 'Loading' status for the module when it starts?

**Comment by johnny-co** [comment]
Another idea, using your browser on the MM rPi connect to your sprinkler's JSON API like this:

http://192.168.0.104/ja?pw=a6d82bced638de3def1e9bbb4983225c&sid=0&en=1&t=600

the pw is an md5hash. if you did not change the default opendoor password then this string will work as is once you replace with your IP address. Otherwise goto https://www.md5hashgenerator.com/ to generate your password hash using your password.

you should get something like this:
{"settings":{"devt":1589303529,"nbrd":1,"en":1,"sn1":0,"sn2":0,"rd":0,"rdst":0,"sunrise":391,"sunset":1208,"eip":1183805101,"lwc":1589296467,"lswc":1589296467,"lupt":1589214690,"lrbtc":4,"lrun":[5,1,468,1589278435],"RSSI":31,"loc":"30.06572,-95.53552","jsp":"https://ui.opensprinkler.com/js","wsp":"weather.opensprinkler.com","wto":{"h":100,"t":100,"r":100,"bh":30,"bt":69.98,"br":0,"pws":"","key":""},"ifkey":"","wtdata":{"wp":"DS","h":57.42,"p":0,"t":71.5,"raining":0},"wterr":0,"curr":0,"sbits":[0,0],"ps":[[0,0,0],[0,0,0],[0,0,0],[0,0,0],[0,0,0],[0,0,0],[0,0,0],[0,0,0]]},"programs":{"nprogs":2,"nboards":1,"mnp":40,"mnst":4,"pnsize":32,"pd":[[51,0,2,[16384,2,90,0],[600,600,300,600,600,600,0,0],"Morning Sprinklers"],[3,8,0,[770,0,0,0],[0,0,0,300,0,0,300,300],"Test Program"]]},"options":{"fwv":219,"tz":28,"ntp":1,"dhcp":0,"ip1":192,"ip2":168,"ip3":0,"ip4":104,"gw1":192,"gw2":168,"gw3":0,"gw4":254,"hp0":80,"hp1":0,"hwv":32,"ext":0,"sdt":0,"mas":0,"mton":0,"mtof":0,"wl":78,"den":1,"ipas":0,"devid":0,"uwt":1,"ntp1":192,"ntp2":168,"ntp3":0,"ntp4":104,"lg":1,"mas2":0,"mton2":0,"mtof2":0,"fwm":3,"fpr0":100,"fpr1":0,"re":0,"dns1":192,"dns2":168,"dns3":0,"dns4":254,"sar":0,"ife":0,"sn1t":0,"sn1o":1,"sn2t":0,"sn2o":1,"sn1on":0,"sn1of":0,"sn2on":0,"sn2of":0,"subn1":255,"subn2":255,"subn3":255,"subn4":0,"wimod":42,"reset":0,"dexp":0,"mexp":8,"hwt":172},"status":{"sn":[0,0,0,0,0,0,0,0],"nstations":8},"stations":{"masop":[255],"masop2":[0],"ignore_rain":[0],"ignore_sn1":[0],"ignore_sn2":[0],"stn_dis":[0],"stn_seq":[255],"stn_spe":[0],"snames":["1-Corner Flowers/Patio Lawn","2-Front Flowers/Patio Flowers","3-Driveway Side Lawn/Back Yard","4-Front Lawn","5-Side From Street","6-Side Lawn From House/Back Yard","S07","S08"],"maxlen":32}}

**Comment by RStadlmair** [comment]
Thanks for your efforts, update from my side.
I have a test-MM which i updated to the latest MagicMirror version today.
Installed your module there from scratch (newest code) and used your default config from Readme.MD

Still no view - also no loading screen showing up.
Also entering my OpenSprinkler didnt work.
Direct URL API call from the browser works both with DNS and IP Address from that box.

I have set my Raspberry to german lanuage settings (keyboard ...) maybe this is an issue ?

**Comment by johnny-co** [comment]
Without the 'Loading' text showing up, it really sounds like there is an error in potentially the config file like a mispelling or missing bracket, etc.
Start with the basic config checker:
Open a terminal
Type cd MagicMirror and press Enter
Now you’re in the MagicMirror directory
Type npm run config:check and press Enter
MagicMirror will now check your config

Likely not an issue but worth checking anyway. I have also found MM sends entries to the browser console like Starting module xxxx..... loading, etc. To access it,
with the MM running, click Control-Shift-I , that should bring up a debugging screen, click on the Console tab. Then reload (Control-R) and see if you are getting any significant errors like cant find MMM-OpenSprinkler module and similar. fyi i get a few CSS load error from MM core but that appears to be just MM team needing to do a little house cleaning and does not appear to affect the MM from running.

I dont know of any inherent issues with regional settings on RPI, german has the same 26 letters plus a few extras as english.

**Comment by RStadlmair** [comment]
Hi johnny-co! I updated MM to its latest version now, also npm is now updated. Still no-show, BUT your hint with debug-mode helped to get an error message (see screenhot below): 
![grafik](https://user-images.githubusercontent.com/22378822/82059822-d9ccf380-96c6-11ea-8bc4-937fca4b1505.png)

Dows this give you a hint ?

**Comment by johnny-co** [comment]
Thats it! Look at the first error. It says cant load :8888/modules/MMM-????-OpenSprinkler.js
You have funky characters between MMM and OpenSprinkler
My guess is that is in your config file. maybe you are inadvertently using a special german character instead of the dash (for my keyboard that is the key to the right of the -0- number key).

The other two errors are safe to ignore:
#2 i get that same stylesheet error
#3 looks the weather module is looking for a valid key

**Comment by RStadlmair** [comment]
Ok, seems we are in the next phase. reTYPED the Module name (and not copied it from the folder - how weird !!) now we are a litle further:
![grafik](https://user-images.githubusercontent.com/22378822/82068663-91b3ce00-96d2-11ea-9982-b73dcdd4704b.png)
with this config. 
(Access to demo.opensprinkler works from the browser.)
![grafik](https://user-images.githubusercontent.com/22378822/82068740-b14af680-96d2-11ea-9937-eceb65b2679e.png)

**Comment by johnny-co** [comment]
found your other issue. you did your git clone wrong. It is case sensitive.
Go into modules folder and delete your MMM-Opensprinkler folder
then do the git clone again. pay attention to the capital letters:

git clone https://github.com/johnny-co/MMM-OpenSprinkler.git

After i cloned and restarted MM it started working!!!! from a clean computer on my end.

**Comment by RStadlmair** [comment]
johnny-co, MANY THANKS - that did the trick! immediately worked after that last action. 
Love that module. Keep on the good work !
![grafik](https://user-images.githubusercontent.com/22378822/82079487-376f3900-96e3-11ea-8595-7e0801357ee3.png)
